#! /usr/bin/bash

function preview_for() {
    old=$(pwd)
    cd $1
    make
    lastpage=$(($(pdfinfo $2.pdf | awk '/^Pages:/ {print $2}')-1))
    convert -dither FloydSteinberg -density 300 "$2.pdf[0,1,2,3,6,13]" temp%d.png
    montage temp0.png temp1.png temp2.png temp3.png temp6.png temp13.png -tile 3x2 -geometry +0+0 "${old}/$2.png"
    rm -f temp0.png temp1.png temp2.png temp3.png temp6.png temp13.png
    cd "${old}"
}

preview_for examples/one-level one-example
preview_for examples/two-levels two-example